name: Minify CSS

on:
  push:
    branches:
      - main # Remplace par 'master' si besoin
    paths:
      - 'CSS/Jellyfin-CSS-Custom.css'

jobs:
  minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Créer le dossier de sortie
        run: mkdir -p dist/CSS

      - name: Minifier le CSS avec Clean-CSS
        run: npx clean-css-cli -o dist/CSS/Jellyfin-CSS-Custom.min.css CSS/Jellyfin-CSS-Custom.css

      - name: Commiter et pousser le fichier minifié
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'auto: minification du fichier CSS'
          file_pattern: 'dist/CSS/Jellyfin-CSS-Custom.min.css'
